In [1]:
import pandas as pd

In [5]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [7]:
data = [10,20,30,"A"]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3     A
dtype: object


In [9]:
data = [1,2,3,4]
i = ["G.","S","A","I"]
series = pd.Series(data,index=i)
print(series)

G.    1
S     2
A     3
I     4
dtype: int64


In [13]:
data= {"a":10,"b":20,"c":30}
series=pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [15]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [19]:
import numpy as np
data=np.array([100,200,300])
series=pd.Series(data,index=["G","S","V"])
print(series)

G    100
S    200
V    300
dtype: int32


In [23]:
import pandas as pd
data={"Name":["Gowtham","Rahul","Rajesh"],"Age":[38,28,47],"Country":["USA","UK","JAPAN"]}
df=pd.DataFrame(data)
print(df)

      Name  Age Country
0  Gowtham   38     USA
1    Rahul   28      UK
2   Rajesh   47   JAPAN


In [27]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array, columns=["S","A","I"])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   S  A  I
0  1  2  3
1  4  5  6
2  7  8  9
